# docker-compose.yml
# Define o ambiente de laboratório para testar o script QueryMetrix.

version: '3.8'

services:
  db_test:
    image: postgres:14-alpine  # Imagem oficial, leve e específica (versão 14)
    container_name: querymetrix_db_test
    restart: always
    environment:
      - POSTGRES_USER=querymetrix_user
      - POSTGRES_PASSWORD=a_very_secure_password # Mude para uma senha segura
      - POSTGRES_DB=querymetrix_test_db
    ports:
      - "5432:5432" # Mapeia a porta 5432 do container para a porta 5432 da sua máquina
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Volume para inicializar o banco com a extensão pg_stat_statements
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all


volumes:
  postgres_data: